### ISSUE TITLE
Error when using Add-WordCustomProperty

### ISSUE THREAD

**Issue by ch0wm3in** [EvotecIT/PSWriteWord#39]
Hi, 
Awesome module, thanks!
I have some problems though with the new version

Error:
New-Object : Cannot find type [CustomProperty]: verify that the assembly containing this type is loaded.
At C:\Program Files\WindowsPowerShell\Modules\PSWriteWord\1.1.6\PSWriteWord.psm1:1094 char:23
+ ... mProperty = New-Object -TypeName CustomProperty -ArgumentList $Name,  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand

Version: 1.1.6

Expected behavior: 
Same script i have works in 1.0.2 with Add-WordCustomProperty, but not in 1.1.6 but stuff like add-wordtable works.

**Comment by PrzemyslawKlys** [comment]
In version 1.1.0 I've changed approach a bit. Please read https://github.com/EvotecIT/PSWriteWord changelog in regarding namespaces. 

It seems I've forgotten to update this for CustomProperty. Let me fix it up.

**Comment by PrzemyslawKlys** [comment]
Published new version with fix.
